territorios:
  - codigo_ibge: "1302603"
    municipio: "Manaus"
    uf: "AM"
    label: "Manaus/AM"
  - codigo_ibge: "1300607"
    municipio: "Benjamin Constant"
    uf: "AM"
    label: "Benjamin Constant/AM"
  - codigo_ibge: "1501402"
    municipio: "Belém"
    uf: "PA"
    label: "Belém/PA"
  - codigo_ibge: "1506807"
    municipio: "Santarém"
    uf: "PA"
    label: "Santarém/PA"
