municipios_projeto:
  "1302603":
    municipio: Manaus
    uf: AM
  "1300607":
    municipio: Benjamin Constant
    uf: AM
  "1501402":
    municipio: Belém
    uf: PA
  "1506807":
    municipio: Santarém
    uf: PA
